[workspace]
members = [
  "programs/credit_line",
  "programs/collateral_vault",
  "programs/receivables",
  "programs/advance_pool"
]

[provider]
cluster = "devnet"
wallet  = "id.json"

[programs.localnet]
credit_line = "2DgViSNpi9CLMHjLmzqJGHvTGMjZXo97pMufmXJuqAQs"
collateral_vault = "6UB2YQb1VN5fT99vVKX8LQ2YGnSQAALguPdikQtEpjaY"
receivables = "89YkmHwfwtzEAoARKQ3m3QhLaYuJiBrKzYZrbZ6B8DGc"
advance_pool = "8zKbc5hProPy7xB2M5iDKABCLhcb68ezdyAixiC7NcDe"

[programs.devnet]
credit_line = "2DgViSNpi9CLMHjLmzqJGHvTGMjZXo97pMufmXJuqAQs"
collateral_vault = "6UB2YQb1VN5fT99vVKX8LQ2YGnSQAALguPdikQtEpjaY"
receivables = "89YkmHwfwtzEAoARKQ3m3QhLaYuJiBrKzYZrbZ6B8DGc"
advance_pool = "8zKbc5hProPy7xB2M5iDKABCLhcb68ezdyAixiC7NcDe"

[scripts]
test = "ts-mocha -p tsconfig.json -t 1000000 tests/**/*.ts"

[registry]
url = "https://anchor.projectserum.com"

[toolchain]
anchor_version = "0.32.1"
