[workspace]
members = [
  "programs/credit_line",
  "programs/collateral_vault",
  "programs/receivables",
  "programs/advance_pool"
]

[provider]
cluster = "localnet"
wallet  = "/home/inteli/Documentos/2ANO/HACKATHON/Cronia/Documentos/2ANO/id.json"

[programs.localnet]
credit_line = "2G2o3qfJPDZu4vuNiefEDZbbD6d2zjhRMhzkTmfy9W7T"
collateral_vault = "eCqMvz2YpSLpDmczgbpEkeRhBCm3ivHpmp8NZELvhJb"
receivables = "89YkmHwfwtzEAoARKQ3m3QhLaYuJiBrKzYZrbZ6B8DGc"
advance_pool = "8zKbc5hProPy7xB2M5iDKABCLhcb68ezdyAixiC7NcDe"

[scripts]
test = "ts-mocha -p tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.32.1"
