[workspace]
members = [
  "programs/credit_line",
  "programs/collateral_vault",
  "programs/receivables",
  "programs/advance_pool"
]
resolver = "2"

[profile.release]
overflow-checks = true

[workspace.dependencies]
anchor-lang = "=0.32.1"